In [19]:
# NOUHA LAMRANI     LAM21490091

import numpy as np

while True:
    try:
        n = int(input("Please input the size of the environment (>=3): ")) #Entering the size of environment
        if n < 3: #if statement if the size is less than 3
            print("Invalid input, please try again.") #print error message 
            continue
        break
    except ValueError: #for any value error 
        print("Invalid input, please try again.")

while True:
    try:
        num_of_dirt = int(input("Enter the number of dirty locations: ")) #ask for the number of the dirty locations
        if num_of_dirt < 0 or num_of_dirt > n * n: # if statement fot if the number of dirty location is negative or bigger than the square of the size of the environment
            print("Invalid input, please try again.") #print error message
            continue
        break
    except ValueError: #for any value error
        print("Invalid input, please try again.")

dirt = []
for i in range(num_of_dirt): 
    while True:
        location = input(f"Please input the location of dirt {i+1}  between (0, 0) and ({n-1}, {n-1}) without brackets (for example: 1,2): ") #ask to input the coordinates of the dirt
        try:
            x, y = map(int, location.split(",")) 
            if x < 0 or x >= n or y < 0 or y >= n:  #if statement for wrong input
                print("Invalid input, please try again.")
                continue
            dirt.append((x, y))
            break
        except ValueError: #for any value error
            print("Invalid input, please try again.")

environment = np.zeros((n, n)) #put 0 for clean locations and 1 for dirty locations
for i, j in dirt:
    environment[i][j] = 1

# print the initial environment
print("the Initial environment:")
print(environment)


# Task 2: Define the cleaner
class Cleaner:
    def __init__(self, x, y): # Constructor method, takes starting position arguments
        self.x = x
        self.y = y

    def move_left(self):  # Move left method, decrements y attribute
        self.y -= 1

    def move_right(self): # Move right method, increments y attribute
        self.y += 1

    def move_up(self):  # Move up method, decrements x attribute
        self.x -= 1

    def move_down(self):  # Move down method, increments x attribute
        self.x += 1

    def clean(self, environment):    # Clean method, sets current position in environment to 0
        environment[self.x][self.y] = 0

    def is_goal_state(self, environment): # Goal state check method, returns True if environment fully cleaned
        return np.sum(environment) == 0

# Task 3: Run the agent
while True:
    cleaner_location = input(f"Please input the start location of the cleaner between (0, 0) and ({n-1}, {n-1}): ") #ask for the start location of the cleaner
    try:
        x, y = map(int, cleaner_location.split(","))
        if x < 0 or x >= n or y < 0 or y >= n:           
            print("Invalid input, please try again.")
            continue
        if environment[x][y] == 1: #if the start location is the same as the location assigned for dirt try again
            print("The start location of the cleaner cannot be on the dirt, please try again.")
            continue
        cleaner = Cleaner(x, y)
        break
    except ValueError: #for any value error
        print("Invalid input, please try again.")

# print the initial state
print(f"Initial state: the cleaner is at ({cleaner.x}, {cleaner.y}))")
print(environment)

while not cleaner.is_goal_state(environment):  # While the goal state has not been reached
    if environment[cleaner.x][cleaner.y] == 1:   # If the current position has dirt
        cleaner.clean(environment)  # Clean the current position
        print("Dirt getting cleaned")
    else:
        if cleaner.y > 0:   # if to dirt, try to move to a close position
            cleaner.move_left()
            print("Move left")
        elif cleaner.y < n-1:
            cleaner.move_right()
            print("Move right")
        elif cleaner.x > 0:
            cleaner.move_up()
            print("Move up.")
        elif cleaner.x < n-1:
            cleaner.move_down()
            print("Move down.")
        print(f"Cleaner at ({cleaner.x}, {cleaner.y})")
        print(environment)
     
# When the goal state is reached
print("Task completed!")



Please input the size of the environment (>=3): 3
Enter the number of dirty locations: 1
Please input the location of dirt 1  between (0, 0) and (2, 2) without brackets (for example: 1,2): 1, 1
the Initial environment:
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Please input the start location of the cleaner between (0, 0) and (2, 2): 1, 2
Initial state: the cleaner is at (1, 2))
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Move left
Cleaner at (1, 1)
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Dirt getting cleaned
Task completed!
